### ISSUE TITLE
Handouts are buggy, showing up on every lesson plan

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#1063] opened 2022-07-25 03:48 UTC
Every lesson on the web has the design recipe pages in the materials section.

This is what the materials section for numbers inside video games looks like... and it's not how the lesson currently builds in our repository
![Screen Shot 2022-07-24 at 10 44 22 PM](https://user-images.githubusercontent.com/66691020/180695049-625527d3-375a-4872-96ea-6209b8930f6f.png)

**Comment by schanzer** [comment] 2022-07-25 10:27
@flannery-denny The title of an issue should be descriptive, indicating what the issue is about. "Website needs to be updated' doesn't say what the problem is, and in this case is not accurate: this is _exactly_ how the lesson builds in our repository.

@ds26gte something is wrong with the new `@handout{}` directive -- handouts are showing up in lessons where they shouldn't.

**Comment by ds26gte** [comment] 2022-07-25 11:17
I believe this was fixed in 63847671e

**Comment by flannery-denny** [comment] 2022-07-25 11:33
@schanzer ‘git pull’. I double checked before creating the issue that @ds26gte had fixed the bug.

Flannery

**Comment by schanzer** [comment] 2022-07-25 11:55
@flannery-denny ahh - that's the part I missed. Thanks! Rebuilding and updating now...

**Closed by schanzer** 2022-07-25 11:55 UTC
Labels: Infrastructure
