### ISSUE TITLE
Please don't fix yet - but after the 2022 release let's address the fact that a 5em ?FITB is a different length than @fitb{5em}

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#920] opened 2022-06-05 15:30 UTC
for an example see `functions-make-life-easier/pages/rs.adoc`

**Comment by schanzer** [comment] 2022-06-07 11:58
Thanks for flagging, @flannery-denny. This is a good CSS bug!

At first I thought this was easy: in `rs.adoc`, you are writing code that is formatted as regular text:
```
*fun* rs(@fitb{5em}{}) *:* @fitb{8em}{}(@fitb{30em}{}) *end*
```

Code uses a different font than regular text, so `1em` has a different meaning. It's logical that this would wind up being a different width! So I started by formatting the code correctly:
```
`*fun* rs(@fitb{5em}{}) *:* @fitb{8em}{}(@fitb{30em}{}) *end*`
```
But this didn't fix the issue! Turns out that AsciiDoctor has its own formatting for inline code blocks (literally anything inside backticks, like the "fixed" code above). Bold elements (like `*strong*`) have a padding, and the font-size is sliiiightly larger than it is in our block-code elements (anything inside `@show{(code...)}`). 

Overriding both of these defaults makes the fitbs behave identically. I pushed a fix **just for rs.adoc**, in order to document what the issue is. After workbooks go to print, I'll move these fixes to `shared.css` so they will impact every page -- and we'll have plenty of time to check the pages to see if any spacing gets messed up.

This fixed the width issue perfectly, but we're not done. There was also some left-hand padding to be removed. This was an easy fix, and can safely be implemented for every page.

**Closed** 2022-08-03 15:06 UTC
