### ISSUE TITLE
Create slide for facilitation of the pre-diagnostic first day of PD

### ISSUE THREAD

**Issue by joystraub** [bootstrapworld/curriculum#2020] opened 2024-04-09 21:41 UTC
Add a slide to first day PD sessions with link to the Pre-Diagnostic and clear explanation geared to lowering teacher anxiety and outlining purpose of the tool, including teachers being able to compare this to their post-diagnostic results.  @schanzer to assign

**Comment by schanzer** [comment] 2024-05-07 16:41
This is duplicate of one of the checklist items in #1397

**Closed by schanzer** 2024-05-07 16:41 UTC
