### ISSUE TITLE
@ifnotsoln{@image}} @ifsoln{{@image}} on the same line does not work

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#2141] opened 2024-08-08 14:15 UTC
Images load if we type
`@ifnotsoln{@image{../images/blank-0to80-num-line-numbered.png}}` 
`@ifsoln{@image{../images/smith.png}}`

But we only get descriptions if we use

`@ifnotsoln{@image{../images/blank-0to80-num-line-numbered.png}} @ifsoln{@image{../images/smith.png}}`

**Comment by schanzer** [comment] 2024-08-08 14:24
@ds26gte 10 bucks says this is because the closing brace if the first @ifnotsoln is swallowing whitespace, causing the directives to bleed together

**Comment by ds26gte** [comment] 2024-08-08 14:58
Not able to duplicate. Since the example prose is not pushed, I tried a similar couple of images in the sample lesson. If you still have the problem, you may want to push your adoc file, and I can re-check.

**Comment by schanzer** [comment] 2024-08-08 15:00
Apologies, @ds26gte - this is on the `boxplots` branch. You can see the problem (and the workaround fix) in [this commit](https://github.com/bootstrapworld/curriculum/commit/cbd71d505dc1f5dca9d1156642412a75974ea41d)

**Comment by ds26gte** [comment] 2024-08-08 15:23
I tried with no space, one space, one newline between the two `@if...{@image{...}}` and can't replicate. When I hover over the image, I continue to get a description popup. (DId I just save myself $10?)

**Comment by schanzer** [comment] 2024-08-08 15:25
Zoom?

**Comment by schanzer** [comment] 2024-08-08 16:08
@flannery-denny and @retabak turns out this is NOT A BUG! Writing up the explanation because it's subtle, before I close:

- AsciiDoc has multiple ways to display something as code. Backticks ` are one example, and in really ancient versions of our materials you may have even seen `----` used as a fence around long codeblocks. 
- But there's another way to do it, which is to _simply indent stuff_. Simply putting a space at the beginning of the line is enough to make the rest of the line turn into verbatim code
- In the example above, the `@ifnotsoln{@image}}` directive is removed, because we're in solutions mode. Notice, however, that this **leaves a space at the start of the resulting line!** When the `@image` directive is expanded into a standard AsciiDoc image expression, that leading space at the start of the line tells AsciiDoc to treat it as code.

Removing the space between the two expressions fixes the issue, as expected. But adding a newline does it in a more readable way. But anyway, the point is that this is exactly how it's supposed to work!

**Closed by schanzer** 2024-08-08 16:08 UTC
Labels: Infrastructure
