### ISSUE TITLE
embarrassing errors on landing page - LIVE on website

### ISSUE THREAD

**Issue by retabak** [bootstrapworld/curriculum#909] opened 2022-05-31 18:30 UTC
Collaboration, Mult Bar Charts, Debugging (and a few others?) go to empty lessons. Text box that appears also says "DESCRIPTION HERE."

Also somehow "Intro to CODAP" is showing up?!

**Comment by schanzer** [comment] 2022-05-31 18:31
@retabak Link pls, so I don't have to hunt?

**Comment by retabak** [comment] 2022-05-31 18:34
https://bootstrapworld.org/materials/latest/en-us/#BuildYourOwn

**Comment by retabak** [comment] 2022-05-31 18:36
<img width="689" alt="image" src="https://user-images.githubusercontent.com/87144723/171260462-0568bc95-c1e3-43c1-873b-7ddf5fc2c2a7.png">

**Comment by schanzer** [comment] 2022-05-31 19:03
@retabak Note for the future -- checking out `master` and then doing a force-build does **not** remove the dependency graph info from any other branches you may have (like all the lessons from `fall2022`)!

That's what happened here -- I did a force-build from master and updated everything...but that included the graph for fall2022 and all the lessons it contains.

I believe the issue is now fixed. Close if it looks good to you?

**Comment by retabak** [comment] 2022-05-31 19:27
It looks the same to me? Did you push?

**Comment by retabak** [comment] 2022-06-06 12:24
reopening this issue because this clicking on "Probability and Inference" (see image below) takes users to an empty page. The scrollover box also says "DESCRIPTION HERE" when it appears.

I'm concerned something weird is going on again. I also got two share requests for CODAP lesson slides this weekend, and CODAP lessons should not be live on our site at the moment.

https://bootstrapworld.org/materials/latest/en-us/

<img width="389" alt="image" src="https://user-images.githubusercontent.com/87144723/172159761-382ef2fd-e8fa-47e2-a0f0-4c2affd6ad70.png">

**Comment by schanzer** [comment] 2022-06-06 13:35
NONE of this should be public. I haven't touched the "latest" shortcut since December. Investigating...

**Comment by schanzer** [comment] 2022-06-06 13:44
@retabak fixed. Yet again.

**Comment by schanzer** [comment] 2022-06-06 18:28
Because it's on the web.

**Closed** 2022-06-06 18:29 UTC
