### ISSUE TITLE
hardcoding in a title slide that is not DS logo?

### ISSUE THREAD

**Issue by retabak** [bootstrapworld/curriculum#1912] opened 2024-02-27 18:17 UTC
OK - I still have this issue in Early Math and Projects where the opening title slide is automatically the Data Science Logo, which is always wrong for Early Math slide decks and often wrong for Project slide decks.

After seeing issue #1849, I played around with `@slidebreak{Core Title Slide}`  (that's the template I want, as we do not have an Early Math logo) but couldn't quite make it do what I wanted. The best I could figure out how to do was get an additional slide with the BS logo which says "notsetyet" at the top. This "notsetyet" slide appears *after* the DS title slide. (This result occurred when I added `@slidebreak{Core Title Slide}` after the lesson table.)

And so, my question is, now that we have the option of `@slidebreak{extra argument}`, is there anyway for a title slide (which I specify) to replace the automatically generated DS title slide?

I'm also wondering if I should just add the "notsetyet" slide to all of the Early Math slide decks and some of the Project decks because it would be clear signal to authors to manually adjust. (Right now, it is VERY easy to forget to change the title slide.) Is that crazy?

If this remains impossible (as it was the last time I asked), feel free to close the issue.

**Comment by flannery-denny** [comment] 2024-02-29 20:04
I have another use case... 
Sometimes I need to define a slide template at the beginning of a lesson section... 
since the "slidebreak" is already implied by the switch from launch to investigate I don't have an opportunity to be proscriptive.

**Comment by schanzer** [comment] 2024-03-01 02:25
@retabak I've pushed a commit that will default to Core for Early Math. 

@flannery-denny can you set up __sample-lesson or zample-lesson to reproduce the version of the issue you're seeing?

**Comment by flannery-denny** [comment] 2024-03-01 16:32
@ds26gte @schanzer Here's a case where the slide has images that belong on the right, but the build doesn't see the COE as images. It's totally fine for authors to move them later, but currently authors would have to adjust the font size and positioning of the text by hand in order to fit the images on the right. Ideally I'd be able to tell the build to use slide template LaunchR and the text would be set up ready for the COE to be dragged into place, but, since this is the opening of the section of the lesson plan there's no @slidebreak directive and therefore nowhere to declare the template type.

```
== Top-Down vs. Bottom-Up @duration{20 minutes}

=== Overview
Students explore problem decomposition as an explicit strategy, and learn about two ways of decomposing.

=== Launch


_Top-Down_ and _Bottom-Up_ design are two different strategies for problem decomposition.


@right{@show{(coe '(... (revenue g) (cost g)))}}

*Bottom-Up:* start with the small, easy relationships like `revenue` and `cost` first. How are they connected with the outer circle? You'll get there eventually, but __we can leave it blank for now (`...`)__. In the Lemonade Stand, you defined `cost` and `revenue` first, and then put them together in `profit`. _This is the same approach as building your Circle of Evaluation inside-out!_

@right{@show{(coe '(- ...revenue... ...cost...))}}

*Top-Down:* start with the "big picture" and then worry about the details later. We could have started with `profit` as @show{(code '(- revenue cost))}, and __fill in the details of `revenue` and `cost` later (thus the `...`)__. _This is the same approach as building your Circle of Evaluation outside-in!_

=== Investigate

@lesson-instruction{
Consider the following situation:

_Jamal's trip requires him to drive 20mi to the airport, fly 2300mi, and then take a bus 6mi to his hotel. His average speed driving to the airport is 40mph, the average speed of an airplane is 575mph, and the average speed of his bus is 15mph. Aside from time waiting for the plane or bus, how long is Jamal in transit?_

Take a moment to think: 

- What would your first step be if you were trying to figure out how long Jamal would be transit? 
- What circles would you draw or functions would you define to solve this? 
- Would you work top-down or bottom-up?

Then turn to @printable-exercise{topdown-bottomup-discussion.adoc}.
}

=== Synthesize

- Whose strategy was top-down? How do you know?
- Do you have questions about either of these strategies?
- Which strategy to do you prefer? Why?

@teacher{Make sure that students see _both_ strategies, and have them discuss which they prefer and why.}

```

**Comment by schanzer** [comment] 2024-03-01 17:00
Thanks, @flannery-denny , this is super helpful.

@ds26gte can your image scanner also look for `@show{(coe )`, when determining slide layout? That would solve for the use-case nicely.

**Comment by ds26gte** [comment] 2024-03-01 17:30
I can. However in this case it seems to make no difference as `Launch2` is not a valid slide style and so gets modified to just `Launch`

**Comment by schanzer** [comment] 2024-03-01 17:43
Fair enough. But we should be counting circles as images

**Comment by flannery-denny** [comment] 2024-03-01 18:53
@ds26gte I suggested that it should use `LaunchR` when the COE is on the right, not `Launch2`. Please lmk when you think this example should be working.

**Comment by retabak** [comment] 2024-03-01 18:59
Since this issue is active at the moment, I'm gonna chime in ONE more time...

Is there *any* way to get 'Math Title Slide' to appear in four specific projects, rather than 'DS Title Sllide' (the default)!?

The four projects are: project-flags, project-function, project-logo, and project-video-game.

**Comment by schanzer** [comment] 2024-03-01 19:02
@retabak You could make a "Project Title Slide" in the deck. Then @ds26gte can modify the script to use that for any lesson folder whose name starts with `Project-`

**Comment by retabak** [comment] 2024-03-01 19:16
@schanzer - ah, that's a good idea. What would go on it? Painter's pallette? I'm wondering if maybe projects should just get the Core title slide also.

**Comment by ds26gte** [comment] 2024-03-01 19:17
@flannery-denny , since this slide contains _two_ `@show{(coe ...)}`s, that actually removes the `R`.  I removed one of them and with my change it does produce `LaunchR`

**Comment by schanzer** [comment] 2024-03-04 12:37
Closing since the issue is fixed - we can continue this other request on slack, and open an issue if needed

**Closed by schanzer** 2024-03-04 12:37 UTC
Labels: Infrastructure
