### ISSUE TITLE
slide image count is off again

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#2145] opened 2024-08-13 10:23 UTC
I'm on the boxplot branch in the box-plots lesson. When I force build the slide deck[ I get this](https://docs.google.com/presentation/d/1pwXv-qGH5uY_tTFXgR3APKaue_MnBnw3c1Wp5KDcbGc/edit#slide=id.a31634d0-5997-11ef-bae5-7de4a82b1a97)

1. I just clicked on a link in the presenter notes of slide 14. It opened up an image that comes two images after the image I was expecting to see.

2. Then, somehow, slides 17 & 18 which should use two different images use the same ones. 
3. slide 19 uses the correct image
4. slide 23 uses the wrong image
5. slide 27 uses the correct image

Noting that this lesson plan uses some images within @ifslide{} and others in @ifnotslide{}

**Comment by ds26gte** [comment] 2024-08-14 00:33
Pushed fix to both `master` and `boxplot` branches.

Note: There doesn't appear to be any real need to use the idiom `@ifnotslide{@centered-image{x.png}}` followed by `@ifslide{@image{x.png}}`. `@centered-image`s are converted to `@image`s anyway in slides. The only difference seems to be that `@centered-image`s don't contribute to the image count of the slide (which affects the style of the slide). This seems like a particularly fine hair that's being split. Is it still intentional now?

**Comment by flannery-denny** [comment] 2024-08-14 01:13
Thanks @ds26gte. We often want an image to be centered in the lesson plan and appear on the right in the slides. That’s what I was trying to use those directives for. FlanneryOn Aug 13, 2024, at 8:34 PM, ds26gte ***@***.***> wrote:﻿
Pushed fix to both master and boxplot branches.
Note: There doesn't appear to be any real need to use the idiom @***@***.***{x.png}} followed by @***@***.***{x.png}}. @centered-images are converted to @images anyway in slides. The only difference seems to be that @centered-images don't contribute to the image count of the slide (which affects the style of the slide). This seems like a particularly fine hair that's being split. Is it still intentional now?

**Comment by ds26gte** [comment] 2024-08-14 12:49
Understood. But note that `@image` _does_ contribute to determining if a slide should get a `C`. So you may be getting a centered slide even though you used `@image` inside `@ifslide`. Is that what you want?

As far as I can tell, `@centered-image` doesn't contribute to making a slide centered. @schanzer may need to revisit this logic, which I slavishly followed from the original spec with its tons of exceptions. The function to look at in `make-slides.lua` is `set_imageorientation()` on line 117ff. (The other directive that contributes to a slide's centeredness is `@center`.)

**Comment by flannery-denny** [comment] 2024-08-14 15:18
@ds26gte per our discussion, `@centered-image{}` should contribute to slide layout in exactly the same way as `@center{@image{}}` does. Make it so :) Thanks!

**Comment by schanzer** [comment] 2024-08-16 14:24
@flannery-denny can you check this out and close if the issue is resolve?

**Comment by schanzer** [comment] 2024-08-17 01:53
@flannery-denny I did a force build and walked through the lesson slide-by-slide -- looks like this is fixed!

**Closed by schanzer** 2024-08-17 01:53 UTC
Labels: Infrastructure
