### ISSUE TITLE
Update README tabs for all data science google sheets 

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#1261] opened 2023-01-25 23:03 UTC
We've developed this [template](https://docs.google.com/spreadsheets/d/1aK406vUBWduay5LEmALNb7-JvH55wZm6WY6kQgFADD4/edit?usp=sharing) for README tabs and should use it to bring our existing datasets up to our own standards.

We've also developed this [dataset contribution form](https://bootstrapworld.org/materials/spring2023/en-us/lessons/choosing-your-dataset/pages/contributing-a-dataset.html)

And here's a link to the archived [datasheets for datasets branch](https://github.com/bootstrapworld/curriculum/tree/ARCHIVED-fall2021-with-datasheets) that was the first betatest of making datasheets for our datasets in December 2020.

If a link is busted, search it for on the [Wayback Machine](https://web.archive.org/), use the new link, and acknowledge that the old link is no longer active.

- [x] Global Food Supply & Production
- [x] Global Waste by Country 2019
- [x] World Cities Proximity to Ocean
- [x] Earthquakes
- [x] Air Quality, Pollution Sources & Health in the US
- [x] Health by US County
- [x] Covid in the US by County
- [x] Arctic Sea Ice
- [x] Countries of the world
- [x] Gerrymandering
- [x] Marijuana Laws & Arrest by State 2018
- [x] LAPD Arrests 2010-2019
- [x] NYPD Stop, Search & Frisk 2019
- [x] Refugees 2018
- [x] State Dem
- [x] US Income
- [x] US Jobs
- [x] US Voter Turnout 2016
- [x] Esports Earnings
- [x] MLB Hitting Stats
- [x] NBA Players 
- [x] NFL Passing
- [x] NFL Rushing
- [x] Movies
- [x] IGN video game Reviews
- [x] International Exhibition of Modern Art
- [x] North American Pipe Organs
- [x] Pokemon
- [x] Music
- [x] College Majors
- [x] US Colleges 2019-2020
- [x] RI Schools
- [x] Evolution of College Admissions in California
- [x] Soda Coffee & other drinks
- [x] fast food nutrition

**Comment by schanzer** [comment] 2023-06-01 17:02
@flannery-denny Great idea. go for it.

**Comment by flannery-denny** [comment] 2023-06-01 17:56
@schanzer I have audited all of the README tabs of all of the Google sheets to confirm that they actually provide information and updated them when they didn't. I propose we close the issue as is. If you would rather devote several weeks of my time to converting tabs into the format you can see under new README in the food supply data set, let me know.

**Comment by schanzer** [comment] 2023-06-01 17:57
@flannery-denny thanks! I'm comfortable closing this as-is, since the original spirit of the issue is satisfied.

**Comment by flannery-denny** [comment] 2023-06-07 21:21
@schanzer Looking more closely at the State Demographics dataset, it needs you to give us more information. The README tab states that two census documents have been referenced. There are columns in the table labeled 2010 and 2020. There is no indication as to what year the data in columns F-V comes from.  The same information belongs in a comment in the starter file.

**Comment by schanzer** [comment] 2023-06-08 03:07
@flannery-denny good catch! I've updated the readme and starter file to include information from https://web.archive.org/web/20170314231421/http://think.cs.vt.edu:80/corgis/csv/state_demographics/state_demographics.html, which says that F-V used data summarized in 2015.

**Comment by schanzer** [comment] 2023-07-08 14:16
@flannery-denny can you update the description to describe what work remains here? If there's none, we should close the issue.

**Comment by flannery-denny** [comment] 2023-07-13 02:07
@schanzer It has been on our one-on-one agenda for quite some time to discuss the readme tabs because you said you would like to update the formatting of a few per month and before I am willing to believe that it is a good use of my time, I think we need to write a clear spec for which datasets we care about and what our expectations are. all previous thinking about what the ideal readme tab might look like lives in this issue. Unless we decide that we are satisfied with readme tabs for all current datasets as is and only plan to do better with future datasets, this issue needs to remain open.

**Closed** 2023-08-08 18:38 UTC
Labels: Data Science
