### ISSUE TITLE
Figure out how to link to contracts in non-pathway lesson plans

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#1398] opened 2023-06-20 18:53 UTC
I think we'll also want to be able to link to blank DR pages, Data Cycles, Regression analysis.

**Comment by schanzer** [comment] 2023-06-21 12:55
@flannery-denny I have a few solutions at my disposal, but which one I choose will depend on just how often we need it. Which lessons absolutely need this besides `contracts`?

**Comment by flannery-denny** [comment] 2023-06-21 18:32
- Flags
- Inequalities2
- Making Game Image
- Contracts
- Defining Values
- Function Composition
- Advanced Displays
- Filtering and Building

and, if we actually want to move away from providing contracts it would have to be mentioned in more lessons.

also, making sure you saw my expand description above.

**Comment by schanzer** [comment] 2023-07-03 17:09
@flannery-denny I've added an example in the contracts lesson, which uses a pathway-specific link that is hidden when viewed outside of a pathway. Let me know if you'd like something to change here.

**Comment by flannery-denny** [comment] 2023-07-13 04:19
@schanzer I think this sort of works, except that there's no way to provide wording that only appears if it's the pathway and isn't part of the link text. I think we might also need an `@ifpathway` directive in order to deploy this elegantly.

you've written 
`Decide whether you'd like to provide your students with copies of the @opt-printable-exercise{image-contracts.adoc, image contracts}. @pathway-link{resources/pages/contracts.pdf, You can also point them to the contracts pages from the back of the course book.}`

Outside of the pathway it reads as follows.

<img width="796" alt="Screen Shot 2023-07-13 at 12 18 11 AM" src="https://github.com/bootstrapworld/curriculum/assets/66691020/04e892d4-43aa-4976-854f-661cbce3a34d">




I'd like to write something more like
`@ifpathway{Decide whether you'd like to provide your students with copies of the} @pathway-link{resources/pages/contracts.pdf} @ifpathway{or just}  provide your students with copies of the @opt-printable-exercise{image-contracts.adoc, image contracts}. @ifpathway{(If you're using a printed workbook, the complete contracts for the course are included at the back.)`

**Comment by schanzer** [comment] 2023-07-13 12:52
@flannery-denny JFYI - we already have an `@ifpathway{XYZ}{...}` directive. And it's impossible to create a directive like the one you describe, because lessons - by definition - do not know whether they are being viewed as part of a pathway or not.

If I understand you correctly, here's the text I _think_ you want them to see:
**_In a pathway:_** Decide whether you'd like to provide your students with copies of the **Pathway Contracts Page**, or just the one page **image contracts** handout. (If you're using a printed workbook, the complete contracts for the course are included at the back.)

**_Not in a pathway:_** Provide your students with the one page **image contracts** handout.

Is that roughly what you're getting at?

**Comment by flannery-denny** [comment] 2023-07-23 20:20
@schanzer - Heads up: I renamed the image contacts page as **Contracts for Image-Producing Functions**.

**Comment by flannery-denny** [comment] 2023-07-23 20:21
@ds26gte - Confirming I can use `@pathway-link{resources/pages/contracts.pdf, contracts pages}` inside of `@ifpathway{}`

**Comment by schanzer** [comment] 2023-07-23 21:24
@flannery-denny `ifpathway` shouldn't be relevant to this work (see my earlier comment). Can we chat about what it is you need?

**Comment by flannery-denny** [comment] 2023-07-23 21:45
@schanzer I did a fresh pull and it was being used in the contracts lesson, which it seemed had been edited since my last look. And the comment I'm looking at from you says
<img width="472" alt="Screen Shot 2023-07-23 at 5 44 21 PM" src="https://github.com/bootstrapworld/curriculum/assets/66691020/10d316f3-9a6b-4832-a7c8-ce32040bba16">

**Comment by flannery-denny** [comment] 2023-07-25 01:26
@schanzer I'm not convinced that it serves us to direct people to contracts pages rather than provide code in measures of center or algebra 2, but those lessons now use 
`@pathway-link{resources/pages/contracts.pdf, Contracts pages}`

**Comment by flannery-denny** [comment] 2023-07-25 01:36
@schanzer I'm not convinced that it serves us to direct people to contracts pages rather than provide code in measures of center or algebra 2, but those lessons now use 
`@pathway-link{resources/pages/contracts.pdf, Contracts pages}`

You can click on the last commit to see the instances in question.

If you like this solution, the issue is ready to close.
If you'd like me to provide code in those lessons instead, let me know.

**Comment by schanzer** [comment] 2023-07-25 02:30
I don't think this commit quite gets us there. It really looks like either I or @ds26gte need to spend some time developing a more flexible directive for this...

**Comment by flannery-denny** [comment] 2023-07-25 06:30
@schanzer happy for you to make the new directive that I attempted to spec weeks ago, back when I built something you pushed and saw the missing text issue. Sounded like it was going to be a perhaps untenable amount of work and we shouldn’t have the directive unless we really needed it. I’ve pushed these changes to create a record of use cases and to highlight that the alternatives would be to A) provide contracts in lesson materials we expect will be mixed and matched (I honestly don’t see the harm - isn’t the point to be able to use contracts, rather than to be able to find contracts in a dictionary?)B) assume some lessons would only be taught from within a pathway so it doesn’t matter whether text would drop out when the lesson is not viewed from within a pathway.On Jul 24, 2023, at 10:31 PM, Emmanuel Schanzer ***@***.***> wrote:
I don't think this commit quite gets us there. It really looks like either I or @ds26gte need to spend some time developing a more flexible directive for this...

**Comment by schanzer** [comment] 2023-08-01 20:45
@flannery-denny @retabak here's a wild idea:

What if we just have a master contracts page that includes the _complete set of all contracts_ used across all our curriculum, which is accessible (and searchable!) from the web? Lessons in standalone mode point there, and lessons in pathway mode refer to the pathway-specific contracts pages.

That greatly simplifies the prose in each lesson, since we are _always_ referring to a "contracts page". The only thing that needs to change is the link.

**Comment by flannery-denny** [comment] 2023-08-01 21:28
@schanzer Seems like a good solution for me. I like the idea that students who are accessing contracts outside of pathways could discover and use functions that there teachers weren't directly teaching them about. And it being searchable makes the enormity of the list feel manageable.

In some dreamworld perhaps when students were accessing pyret from the bootstrap context the documentation link in the drop down menu would point to this searchable contracts page ;)

**Comment by schanzer** [comment] 2023-08-09 04:23
@flannery-denny this REALLY feels like a duplicate of #1453. ok to close?

**Closed** 2023-08-09 12:48 UTC
Labels: Infrastructure
