### ISSUE TITLE
Design recipe page titles aren't being consistently calculated and used

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#1363] opened 2023-05-11 20:17 UTC
Update from Emmanuel:

It's not about slides -- this happens in the lesson plans too. _Sometimes_, DR pages don't have their titles available when @printable-exercise link generation happens.

--------------
I am still not able to build the slides for the `Inequalities-Collision` lesson and have the link to the DR page build as expected. Instead I am seeing `pages/collision.adoc`
<img width="1217" alt="Screen Shot 2023-05-11 at 3 09 54 PM" src="https://github.com/bootstrapworld/curriculum/assets/66691020/af9b411d-f9e9-4e1a-856f-7de92d362f08">

**Comment by flannery-denny** [comment] 2023-05-11 20:19
I am going to make the fix by hand for this one deck, but I would like to see the build issue resolved.

**Comment by schanzer** [comment] 2023-05-12 01:57
@flannery-denny I did a forced make and then built with `./build-slide -f inequalities-collision`. Even building ten times, I could not reproduce this issue. Every time, the slide in question renders like this:

![image](https://github.com/bootstrapworld/curriculum/assets/77126/344c30f6-b979-491a-b440-b3efc87544a2)

Are you absolutely sure you're doing this with `-f`? If so, maybe I'm not understanding the issue. Is it _subsequent, unforced_ builds that trigger this?

**Comment by flannery-denny** [comment] 2023-05-12 14:54
@schanzer Just had the same issue on the last slide of Simple Inequalities

**Comment by schanzer** [comment] 2023-05-16 02:49
@ds26gte it just happened to me, while I was working on slides for the `problem-decomposition` lesson. I have two slides that each refer to a different DR page (Revenue and Cost on one, and Profit on the other). I built once and one of the links had the right title, but the other didn't. I built again and the second title appeared, but the first was now missing! 

You can see this on slides 3+4 of [this deck](https://docs.google.com/presentation/d/19r7CdOH65kFPYF4OHLJj42X_XxK37kXMP-_mZYMhiDU/edit#slide=id.92881f91-f393-11ed-b19b-1dcf9c7764d8).

I opened up distribution/lessons/problem-decomposition/pages/.cached/, and found that `.revenue-and-cost.titletxt` had the first title. `.profit.titletxt` **did not even exist!**
<img width="322" alt="image" src="https://github.com/bootstrapworld/curriculum/assets/77126/dc89217d-30d0-4b11-ba85-1d28d048a69b">

Somehow that file is getting clobbered, or perhaps isn't being written at all...and it's happening nondeterministically.

**Comment by schanzer** [comment] 2023-05-16 18:36
@ds26gte steps to reproduce:

1. Do a forced make, then open lesson `XYZ/pages/.cached/`
2. Do an _unforced_ make, and look at the `.cached` folder again. If XYZ contains DR pages, one of those pages' `.titletxt` seems to get deleted

**Comment by schanzer** [comment] 2023-05-16 19:59
@ds26gte this appears to have fixed the issue...or at least helped it. I just rebuilt the problem-decomposition lesson a dozen times with no issue. Previously, this would show up every 2-3 builds.

I’m going to tentatively close the issue. We can re-open if it rises again. Fingers crossed....

**Closed by schanzer** 2023-05-16 19:59 UTC
Labels: Infrastructure
