### ISSUE TITLE
Develop initial set of formative assessments for priority lessons (4-5 assessments)

### ISSUE THREAD

**Issue by schanzer** [bootstrapworld/curriculum#1789] opened 2024-01-24 18:21 UTC
Two items we should review / discuss before these assessments go live...

- [x] verify that all questions have correct answers selected for teachers to view only
- [x] I turned off "ask students to explain their responses" from many of the questions, but now that we aren't getting or this data, should we turn it on? (In hindsight, realizing it would be interesting to ask students to explain, whether we use that data as a metric or not.) - @retabak make it so!

[**Histograms**](https://teacher.desmos.com/activitybuilder/custom/6671db339409cfb8815bf875)

Q1: Distinguish between bar charts and histograms
Q2: Create histograms
Q3 + Q4: Interpret histograms
Q5: Choose the correct bin size

- [x] finish image edits
- [x] split into lesson section edits. Then add language and links to the lesson plan

[**Box Plots**](https://teacher.desmos.com/activitybuilder/custom/668d7be8fd7c6212638763d6)

Q1: Compute a 5-number summary from a dataset
Q2: Interpret a 5-number summary
Q3: Interpret a box plot
Q4: Describe box plot shape
Q5: Compare and interpret box plots [maybe we can ditch this question?]
Q6: Connect box plots and histograms

- [x] finish image edits
- [x] split into lesson section edits. Then add language and links to the lesson plan

[**Linear Regression**](https://teacher.desmos.com/activitybuilder/custom/66bf6a408a890dd0d0ea2654)

Q1: Draw and interpret predictor functions
Based on what was there, Flannery split this into two questions Q1 - direction and strength from scatter plot Q2 - r-value
Is there something else we wanted to assess?
Q3:  Make predictions using a predictor function
Q4: Interpret linear regression

- [ ] finish image edits
- [x] split into lesson section edits. Then add language and links to the lesson plan

[**Threats to Validity**](https://teacher.desmos.com/activitybuilder/custom/66c391955b3af1281567a903)

Q1: Identify selection bias and bias in study design
Q2: Identify poor choice of summary data
Q3: Identify confounding variables

- [x] finish image edits
- [x] split into lesson section edits. Then add language and links to the lesson plan

~ Stretch:**composing table operations**~

**Comment by retabak** [comment] 2024-06-18 19:57
Starting a potentially BIG conversation, which might need to happen in real time:

I think these formative assessments should highlight the most common student misconceptions.  In writing the first formative assessment (histograms), I consulted the literature on misconceptions about histograms, and I discovered that our stuff doesn't quite address these misconceptions. (See #2085.) 

I can ignore the literature and write the formative assessments based on what's covered in our lessons, or.... I can propose revisions to our lessons as I look at the literature. Obviously, I think the latter is the better solution, but it would (of course) be more time-intensive... and might motivate us to do a literature review on all of the various data science topics that we cover. Curious to hear your opinionis re: the feasibility / urgency of this work, @schanzer and @flannery-denny. (I think that focusing on the literature would likely bring us in greater alignment with the Common Core standards, also.)

FWIW: it was VERY easy to find the most common misconceptions about histograms. I just put "histogram misconceptions" in google scholar and read the first four articles. I don't think we need to do any super deep dives.

**Comment by schanzer** [comment] 2024-06-19 13:51
@retabak We don't really have a choice this year. The fall2024 lessons are finalized, and cannot be changed.

We need to do option 1, and add notes to https://github.com/bootstrapworld/curriculum/issues/155 so that we can improve the histogram lesson for fall2025

**Comment by retabak** [comment] 2024-06-19 14:01
That makes sense. I got pretty excited, but it's true, this would totally be a big big project, not to mention that lessons are finalized.

**Comment by retabak** [comment] 2024-06-27 19:43
questions I'm pondering:

- Do we require that all questions are auto-checking? (e.g., desmos does the grading for us!) I am suspecting yes.
- Are we assessing students on their mastery of the coding / Pyret skills? or just on DS concepts?

**Comment by schanzer** [comment] 2024-06-27 23:40
@retabak Yes- auto-checking. Just DS concepts

**Comment by retabak** [comment] 2024-06-28 16:20
Okay! Here is a draft of the histograms formative assessment:
https://teacher.desmos.com/activitybuilder/custom/6671db339409cfb8815bf875

There are a variety of considerations / questions / concerns that I want to share:

- I did my best to align the assessment with the content of the lesson. The four workbook pages in the lesson are on these topics: Summarizing Columns with Bar Charts & Histograms; Making Histograms; Reading Histograms; and Choosing the Right Bin Size. You'll see that the titles of the desmos slides correspond with these worksheet titles. I opted to include 2 questions on Reading Histograms; the first question is lower level, the 2nd question (multiple select) is more difficult.
- Given that we teach students to make a histogram, I thought they should make a histogram (Q2). That said, I don't know how to have that portion of the question be self-checking... but the table is. We could just have them do the table, or we could do a MC question where they choose the histogram that matches?
- I am NOT a pro at using the Computational Layer, and it is very time consuming for me to write the code to make the questions score themselves. Maybe I should invest some time to actually learn how? (I'm a hacker at the moment, just copying other people's code.) Or, alternatively, would it be super duper simple for someone else (Dorai / Emmanuel?) to invest some time in learning desmos CL? (Truly, I have no idea.) I didn't (yet) figure out how to throw error messages to students, such as, "You've entered a word - please just provide a number" -- but I suspect that it is possible.
- On that note, I only know how to get Desmos to indicate if ALL elements of a table are correct, so that is what I have done. If we feel strongly about awarding partial credit.... welp, I'm not sure how we will proceed. The student's screen can indicate a check or an X for each response, but the teacher dashboard cannot.

How are we actually going to access this data? Will we be able to see teachers' dashboards? The teacher dashboard is actually not AT ALL easy to use for data analysis. It doesn't do... well, anything, except give a checkmark or an X for each student's response. In designing the assessment, I think we do need to consider how we will be receiving this data.

**Comment by schanzer** [comment] 2024-07-01 12:11
@retabak this looks AMAZING!! Yes yes yes! I think choosing the page titles was a good idea. I wish I knew some CL, but that's not going to happen any time soon. :( 

As for how we're getting the data: Dan says we can send them an activity URL and a list of teacher Desmos names, and they'll send us back all the student data associated with that activity.

I think this is a really strong start. Let's replicate this for the other lessons this week!

**Comment by retabak** [comment] 2024-07-10 14:42
re:  Dan says we can send them an activity URL and a list of teacher Desmos names, and they'll send us back all the student data associated with that activity.

Cool! I'm wondering if there is there any way to find out if teachers have made a copy + edited the formative assessment activity? Many regular desmos users like to customize things - e.g., they add an intro / check-in slide, they put the assessment at the end of some other sequence of activities, etc, etc. Wondering if there's any way we can still gather this data - or if there is a way to encourage teachers to use OUR activity, without modification?

**Comment by flannery-denny** [comment] 2024-07-10 16:59
@retabak Great start :)
- [ ] I think we could improve the wording of slide 4. For me, **most** means something different from **the majority** so I would find myself guessing about whether or not slide 4 is a trick question.

<img width="1053" alt="Screenshot 2024-07-10 at 11 19 17 AM" src="https://github.com/bootstrapworld/curriculum/assets/66691020/4b5bf03a-cce8-4599-8bb5-12989d6aef62">

- [ ] I also don't see the answer that I would want for slide 5, which would be something less than 100, but not necessarily between 20 and 50, since I can't play with the histogram to know whether or not 50 would be too small. 

<img width="1167" alt="Screenshot 2024-07-10 at 11 24 59 AM" src="https://github.com/bootstrapworld/curriculum/assets/66691020/50c5ac40-1233-426e-9e3a-93889f983199">

- [ ] From the checklist at the top of the issue, it looks like you've drafted a second assessment, but I'm not seeing a link. Please add links next to the items in the checklist as you check them off so that it's easy for anyone reviewing this issue to find the most updated version of things. Thanks!

**Comment by retabak** [comment] 2024-07-10 17:41
@flannery-denny - 

> I also don't see the answer that I would want for slide 5, which would be something less than 100, but not necessarily between 20 and 50, since I can't play with the histogram to know whether or not 50 would be too small.

I hoped students would notice that the largest weight is ~200 or less... which means that a bin size of 20 would produce ~10 bins, and a bin size of 50 would produce ~5 bins. If **you** were unable to notice / reason through that, then it obviously is too hard and needs to change.  Perhaps I should invite students to play with the histogram. (There is a hyperlink to the pyret starter file - but not an explicit invitation.) Would that be adequate? That said, @schanzer said we don't want to test coding ability, so perhaps the premise of this question is faulty to begin with.

> I think we could improve the wording of slide 4. For me, _most_ means something different from the majority so I would find myself guessing about whether or not slide 4 is a trick question.

Lol. For me, "most" and "majority" mean literally exactly the same thing, but I have no objection to you playing with the wording. 

@flannery-denny - I've added a link to the histograms formative assessment. I have not added in CL stuff, but I'm realizing I should probably save that for the end.

**Comment by flannery-denny** [comment] 2024-07-10 18:32
@retabak Here's feedback on boxplots

I'm not able to edit from teacher success and am going to wait until I can to confirm that we got desmos set up correctly.

- [ ] I'd suggest we put the directions re answering with NUMBERS into the column header for both box plots and histograms
<img width="501" alt="Screenshot 2024-07-10 at 1 32 18 PM" src="https://github.com/bootstrapworld/curriculum/assets/66691020/43597d8f-f79d-4d9e-94c5-66d02357bddd">

- [ ] If my understanding of box plots is correct, on slide 2 of boxplots we should change "more than" to "at least"
- [ ] slide 3 
-- there are two symmetric box plots and it's not possible to match them both to the word
-- suggest changing "the four sections of the box plot are equal in size" to something about the data itself, like  "the data appears to be evenly distributed across the range"
-- similarly, suggest changing "there is a long whisker trailing off to the left suggesting potential outliers" to something less leading, like "there are potential outliers at the low end of the range"
- [ ] for slide 5 I would get rid of the words about outliers, as they might lead a student who understands box plots well, but doesn't know how they translate to histograms.

For me, majority is a mathematical term with a clear definition of "more than 50%" and most is a conversational term. When I say, "most of the time Dacks is asleep by 9:30" I mean that it is an exception when he is not. But @schanzer may disagree.

**Comment by flannery-denny** [comment] 2024-07-12 18:56
@retabak Seems you've been pretty interested in this issue, but I know you have a lot of AI on your plate. Checking in about whether you imagine drafting the rest of these this month or are hoping not to have to? Unless @schanzer has rethought this, we need to wrap these up in the next two weeks.

**Comment by retabak** [comment] 2024-07-12 19:05
I do think we should have a conversation as a team about the assessment
drafts that exist so far before we create more of these. That said, I would
love it if you wanted to work on drafting the remaining
formative assessments. (I'm not sure how much you have going on at the
moment, though!)

**Comment by schanzer** [comment] 2024-07-12 19:07
I'm sprinting flat-our through the 22nd. I just wrapped up PD in Bay City and I'm at the airport frantically updating stuff for Algebra 2 next week.

I'd hoped to have drafts ready early enough to give feedback before PD started, but we are where we are and I think it's best to draft the rest so we have something more solid to work from when the dust settles.

**Comment by flannery-denny** [comment] 2024-07-15 18:37
To be clear, if we were not planning to collect aggregated data from these assessments and desmos were capable of sharing more nuanced information about student responses, I would love what @retabak has drafted. But given her astute observation that the information we can see on the teacher dashboard is fairly useless, and our intention to use aggregate data at scale, I believe we need to choose other formats for these questions. I expect the aggregate information we would get back would be misleading, which is far worse than useless.

**Comment by flannery-denny** [comment] 2024-07-16 02:06
I've been thinking more about the checkbox question. Makes most sense to me to convert it to multiple true or false slides. We don't lose anything, since the original question was also just asking students to consider each statement individually and decide whether or not it's true or false, and this way the data collected would become precise and valuable.

**Comment by schanzer** [comment] 2024-08-02 18:57
I'm inclined to agree, @flannery-denny. While seeing 20 slides might seem intimidating at first, as soon as students realize that each slide is a single question I imagine they'll calm down.

**Comment by retabak** [comment] 2024-08-15 17:05
Here's the new and improved 20-slide long box plots formative assessment! Also added a question about computing the five-number summary. 

https://teacher.desmos.com/activitybuilder/custom/668d7be8fd7c6212638763d6

Feel free to offer feedback or change it yourself, @flannery-denny and @schanzer. More coming...

**Comment by retabak** [comment] 2024-08-16 16:46
Here's a linear regression draft:

https://teacher.desmos.com/activitybuilder/custom/66bf6a408a890dd0d0ea2654

It is only three questions at the moment. Based on my overview of the lesson, I think they are addressing the right skills. We said we'd aim for 4-5 questions, so I'm wondering if I should add another question on one of these 3 skills, but using a different dataset.

Curious which question you think is highest priority, here? I'm thinking Q3, esp since there is a single slide on that skill at the moment. It is very annoying finding the right datasets, though!

**Comment by retabak** [comment] 2024-08-19 21:21
Here is a "threats to validity" draft.

https://teacher.desmos.com/activitybuilder/custom/66c391955b3af1281567a903

Noting that it was tricky to write this one, given that every single worksheet we have in this lesson is *exclusively open response*. We can't do open response because desmos can't score open response. 

I thought it might be appropriate to have students choose the threat to validity that is described in such-and-such scenario, but quickly threw out that idea upon remembering how much overlap there is between the different threats (ie, when there's selection bias, there is also generally bias in the study design).

The sort of question I did write (which of the following reprsents selection bias?) is NOT practiced in the lesson, so it feels like I've written a not-entirely-fair assessment. That said, I couldn't think of a better solution. Maybe one of you can!?

**Comment by retabak** [comment] 2024-08-22 16:35
@flannery-denny - just pinging you to let you know I've updated the topmost comment in this issue, as requested

**Comment by flannery-denny** [comment] 2024-08-29 14:38
@schanzer Here's the revised [box plot assessment](https://teacher.desmos.com/activitybuilder/custom/668d7be8fd7c6212638763d6). Let us know if it meets your approval and whether we're still trying to get Kathi's eyes on this and the other 2 remaining assessments.

**Comment by flannery-denny** [comment] 2024-08-29 16:02
@schanzer Here's the revised [threats to validity assessment](https://teacher.desmos.com/activitybuilder/custom/66c391955b3af1281567a903). Let us know if it meets your approval

**Comment by retabak** [comment] 2024-08-29 16:06
@flannery-denny - I *love* the improvements you made to the early questions! This makes me happy.

**Comment by schanzer** [comment] 2024-08-29 16:09
Ooohhh, @flannery-denny these are GREAT! Consider it approved!

**Comment by flannery-denny** [comment] 2024-08-29 17:08
@retabak Based on what I saw in Q1, which you had described as _Draw and interpret predictor functions_, I split  this into two questions:
- Q1 - direction and strength from scatter plot
- Q2 - r-value
- Is there something else we wanted to assess here?

@schanzer I'm less confident this assessment is ready to go.

-  Q1: Keep? Remove? Switch image to one with variables labeled and either a weaker or stronger correlation?
-- I know that it's important to you for students to develop an intuition about the shape and strength of a correlation
-- and I also know that it's important to Shriram that we make it clear that we don't really know until we compute. 

- Q3: Is the font on these graphs and the predictor function large enough to read?
- Q4: Is this really doing anything new? Is there a better way to get at the interpretation than this using multiple choice?

**Comment by schanzer** [comment] 2024-08-29 17:22
@flannery-denny 

Q1 - Keep. What do you dislike about it? 
Q3 - I think it's large enough, especially for kids
Q4 - Agreed that it feels redundant. I think we should cut it.

**Comment by flannery-denny** [comment] 2024-08-30 01:43
@retabak I believe the lesson section is new and valuable and I don’t believe this question is new or valuable (in contrast to how you describe the lesson section, this question is not having students write prose). 

@schanzer and I had talked and agreed that the redundancy was a result of the constraints of assessing with multiple choice questions and I was planning to cut the question now and be done.  Instead, because you’ve made a case for the effort, I will reread the lesson section and give it more thought with a fresh brain. 

It may turn out, however, that we cannot follow the guiding principle you want (an assessment for every section of this lesson) within the constraints of the assessment tool we’re using and the way this lesson was authored.  Perhaps if we’re not expecting to get data anyway, we could create more open-ended desmos assessments for lesson sections that demand them? Perhaps it’s ok to have some lesson sections without assessments (as I have been asking from the getgo)? Or perhaps we need to reconsider where our lessons break into new sections with assessability of each chunk as a guiding principle?

**Comment by flannery-denny** [comment] 2024-09-04 19:55
@retabak while you're tackling this, making sure you saw the last two checkboxes ES added to the issue description

**Comment by retabak** [comment] 2024-09-04 20:37
I added those!

**Comment by retabak** [comment] 2024-09-10 16:50
closing this issue; still need to finalize #2176

**Closed** 2024-09-10 16:49 UTC
Labels: Data Science
