### ISSUE TITLE
Introducing DR in DS?

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#835] opened 2022-04-04 23:17 UTC
There used to be a lesson called defining functions. We've done away with it. Not sure which of the new lessons make sense in DS.
Without Defining Functions, the first encounter with the DR is a starter file with no accompanying workbook page.
It only has two DR pages, amounting 2.5 DR problems for them to work independently. 
Wondering if the best plan is to beef this up? So that they can do functions-make-life-easier and move on to this?

**Comment by schanzer** [comment] 2022-04-06 14:48
Closing as a duplicate of #833

**Closed by schanzer** 2022-04-06 14:48 UTC
