### ISSUE TITLE
literal text

### ISSUE THREAD

**Issue by shriram** [bootstrapworld/curriculum#462] opened 2021-04-19 02:12 UTC
In the student datasheet files, why is this text literal?

```
  [.acknowledgment]
  --
  These materials were developed partly through support of the National Science Foundation, 
  (awards 1042210, 1535276, 1648684, and 1738598). link:https://www.creativecommons.org/licenses/by-nc-nd/4.0/[image:{pathwayrootdir}../../lib/CCbadge.png[], window="_blank"]
```

- Shouldn't this be updated as the boilerplate on the BS site changes?
- Also, it hasn't been proof-read (comma before paren).
- And I'm not sure what the second sentence even means.

**Comment by schanzer** [comment] 2021-04-19 23:38
@shriram if this is a duplicate of #465, can we close?

**Comment by shriram** [comment] 2021-04-19 23:42
Unrelated. This is a question about the *input* file, which is independent of format. It just so happens it's being suppressed in PDF, but it is appearing in HTML (and if we stop suppressing it in PDF, it'll be relevant there too). But in any case, the real question here is about the input file content.

**Comment by ds26gte** [comment] 2021-04-20 12:59
This is not literal in the student file, which is kept and edited in the pathway directory, e.g., `pathways/__sample/langs/en_us/resources/datasheets/datasheet-for-arctic.adoc`.  It is added by the build process from version-controlled content ("boilerplate") in `shared/langs/en-us`, and only shows up finally in the `distribution/` directory.  

Your extract is above from an `.asc` file inside `distribution/`, which is to be considered a temp file. In a recent commit, I've even made these files hidden, so they're not immediately visible to you.

In order to change this content, change the files in `shared/langs/en-us` and rebuild with `-F`.

**Closed** 2021-04-20 16:57 UTC
