### ISSUE TITLE
Image captions are not always making it to slides

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#2025] opened 2024-04-11 18:03 UTC
All of the box plots on slides 9, 10, and 11 of [this deck](https://docs.google.com/presentation/d/1B664B3WaXyZW9ooD3YlP8Fn36--1MuWjHmEZj7rZZcU/edit#slide=id.93a508e5-f82c-11ee-96e9-c9ea8aa7def8) build with caption in the box plots lesson plan. Only some of them are building with captions in slides.
<img width="888" alt="Screen Shot 2024-04-11 at 12 53 22 PM" src="https://github.com/bootstrapworld/curriculum/assets/66691020/2af7c70f-2f15-4c54-acaf-c46f838a49fc">

**Comment by ds26gte** [comment] 2024-04-15 14:42
The images that do get proper captions are those inside tables, which get harvested in toto from the HTML.

I've pushed a fix whereby the caption is added for outside-table images, but we need some styling. Right now, it's just an italicized text following the table, which doesn't look too good.

**Comment by flannery-denny** [comment] 2024-04-15 18:59
@ds26gte Thanks for working on this.  Agreed that [the current solution](https://docs.google.com/presentation/d/1B664B3WaXyZW9ooD3YlP8Fn36--1MuWjHmEZj7rZZcU/edit#slide=id.9ad89390-fb59-11ee-8e55-93406319b20c) doesn't work. 

I like your `.image-figure` proposal, as far as I understand it. Since you better understand the broader implications, I'll let you decide whether or not we should wait for @schanzer to weigh in.

**Comment by schanzer** [comment] 2024-04-16 15:12
@ds26gte your commit does not change the resulting slides.

Also, the problem is for images that fall _inside_ tables, not _outside_. I think you may have fixed the wrong situations.

**Comment by flannery-denny** [comment] 2024-04-16 17:13
@schanzer 
- if you look carefully at slide 9, you will see that the _Even Distribution_ caption is indeed landing behind and to the left of the box plot, as @ds26gte described.
- and, as I understand it, slide 10 is a case of tables - I do see the captions in the right place here.

**Comment by schanzer** [comment] 2024-04-16 17:16
Oh! Sorry, I didn't even see that.

@ds26gte , where is that text on slide 9 coming from? That absolutely should not be visible.
@flannery-denny on slide 10 the caption is "table1". Surely that's not what you want to see?

**Comment by schanzer** [comment] 2024-04-16 19:56
@ds26gte apologies for my previous comment. I was confusing the caption with the description! We should use the same DOM pipeline trick that we currently employ for circles of evaluation and tables.

**Closed** 2024-04-17 20:00 UTC
Labels: Infrastructure

**Comment by ds26gte** [comment] 2024-04-18 14:10
BTW, this is not high priority, but we're generating the `AUTOGEN-*.png` images even for those images and CoEs inside tables, which are never used because the  `AUTOGEN-TABLE*.png` subsumes them.  At this point, this is not incorrect: It is merely extra work, and doesn't affect the sync between how the slide images are numbered and what they refer to in the `images/` directory. 

But we could avoid generating these useless images in the first place. This requires syncing between the Lua and JS code. I can make sure in-table images and CoEs don't contribute to the count and you (ES) should make sure that when you select these elements you always skip past tables.

Again, this is not urgent, but I know how much you (ES) like optimizing.

**Comment by schanzer** [comment] 2024-04-18 14:17
@ds26gte I love this thought! Fortunately, the image generation is extremely fast - and the work required to optimize this is far greater than the time we'd save. I am content. :)
