### ISSUE TITLE
@right directive seems to not work properly?

### ISSUE THREAD

**Issue by retabak** [bootstrapworld/curriculum#1077] opened 2022-08-01 16:18 UTC
When I build any pathway, images that are `@right` are appearing above the text, rather than to the right of it.  Here's a screenshot from ds-intro:

<img width="405" alt="image" src="https://user-images.githubusercontent.com/87144723/182194941-4e67a69e-402f-41bd-b3a1-13f375fcc472.png">

...versus what's on our website:
<img width="431" alt="image" src="https://user-images.githubusercontent.com/87144723/182194670-7ad77a72-0aca-4146-9290-80d061a95943.png">

And here's another instance:
<img width="430" alt="image" src="https://user-images.githubusercontent.com/87144723/182194073-d9749f7a-362c-4e52-b288-e2fce3a9d409.png">

website:
<img width="438" alt="image" src="https://user-images.githubusercontent.com/87144723/182195477-5731033a-2ae8-479b-b01f-2d95fe1a294f.png">

**Comment by schanzer** [comment] 2022-08-01 16:19
@retabak This is a duplicate of another issue. Right now all images are broken, as Dorai and I work to fix a bug that was introduced when adding image captions

**Closed** 2022-08-01 16:19 UTC
