### ISSUE TITLE
Improve warnings about images falling inside presenter notes

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#1895] opened 2024-02-23 20:23 UTC
Just built distance-formula slides and got this. As far as I can tell they are not related to this lesson... and I have no idea how to address them.

WARNING: Using @image inside teacher notes
WARNING: Using @image inside teacher notes

**Comment by schanzer** [comment] 2024-02-24 04:55
@flannery-denny they are indeed related to this lesson, but the warning wasn't comprehensive enough to show you why. 

I've improved the warning to now read:
`WARNING: Using @image{(images/characters-on-grid.jpeg 400)} inside @teacher, @QandA, or @strategy`

An image used in _any_ of those directives will also show up in the _presenter notes_ on Google slides, which of course cannot contain images. The problem is that the warning confused "presenter notes" with "@teacher", resulting in a very confusing author experience!

Close if you're happy. :)

**Comment by flannery-denny** [comment] 2024-02-24 23:02
@schanzer Thanks! 

But didn't we agree that images would end up as links to the images in presenter notes?

**Comment by schanzer** [comment] 2024-02-25 02:53
@flannery-denny good call. done!

**Comment by schanzer** [comment] 2024-02-26 04:07
Forgot to close this. :P

**Closed by schanzer** 2024-02-26 04:07 UTC
Labels: Infrastructure
