### ISSUE TITLE
Flexbox upgrades

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#641] opened 2021-10-20 22:26 UTC
![Screen Shot 2021-10-20 at 5 25 27 PM](https://user-images.githubusercontent.com/66691020/138181083-740db574-bedd-4d85-86e9-c54cb9267e14.png)

**Comment by flannery-denny** [comment] 2021-10-21 16:49
Oh boy! If I could have a `@fitb` finish out to the edge of the line without any guesswork, that would be amazing!

**Comment by schanzer** [comment] 2022-03-17 03:48
[There is now a PR open for this](https://github.com/bootstrapworld/curriculum/pull/807). Low priority, but we can get this done after authoring is over.

**Comment by flannery-denny** [comment] 2022-03-17 12:17
Very cool!

Flannery

**Comment by schanzer** [comment] 2022-04-05 22:03
Closing, since the open PR is now a more up-to-date duplicate of this issue.

**Closed by schanzer** 2022-04-05 22:03 UTC
