### ISSUE TITLE
Slide notes don't work if they are indented

### ISSUE THREAD

**Issue by retabak** [bootstrapworld/curriculum#1273] opened 2023-02-07 15:51 UTC
If I put the text caption like in the first screen shot, it doesn't appear in the built slide deck. If I delete the indent (like in the second screenshot), the deck builds with the caption. I don't remember that being a thing during the last round of slide deck creation? I don't think we want this to be a thing, if we can fix it!

![image](https://user-images.githubusercontent.com/87144723/217293471-3586690c-b81b-4c94-9a37-770d2c16dc52.png)

![image](https://user-images.githubusercontent.com/87144723/217294048-bd253238-2c1b-4f42-b60d-5733c7c16fc5.png)

(if it needs to be this way, okay - I can delete the indent. But it's an extra step.)

**Comment by schanzer** [comment] 2023-03-06 02:41
@retabak this has always been the behavior, but I agree it's annoying!

I pushed a fix to `md2googleslides`, so you should be able to run `npm update` and test. Close if the issue is resolved for you!

**Closed** 2023-03-07 14:24 UTC
Labels: Infrastructure
